WORK_DIR: work
DB:
  START_DATE: 2008-1-1
SELECT:
  PERIOD: 600
  DMA: 150 
  MARKET_CAP_MIN: 100000
  SOUKAN:
    STOCK: [0.97,1]
    STOCK_SAYA: [-0.5,0.5]
    KAISA: [0.6,1]
    KAISA_KAISASAYA: [-0.5,0.5] 
  TRADE_COST_MAX: 1000000
REPORT:
  VIEW_PERIOD: 365

